# GitHub actions workflow for testing pylint-silent.

name: run tests

# Triggers the workflow on push or pull-request events.
on: [push, pull_request]

jobs:
  tests:
    runs-on: macos-latest
    strategy:
      matrix:
        # Run on earliest and latest supported python versions.
        python-version: ["3.8", "3.13"]
        # Run linters and pytests.
        testsuite: ["linters", "pytest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install pip and tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: run linters
        # Linters are only run on the earliest supported python version.
        if: ${{ matrix.python-version == '3.8' && matrix.testsuite == 'linters' }}
        run: tox -e mypy,pep8,pylint,ruff
      - name: run pytest
        if: ${{ matrix.testsuite == 'pytest' }}
        run: tox -e py3-pytest
